pipeline {
   
   agent any
   
   stages {
      stage('GIT poll') {
         steps {
            git url: 'https://github.com/MofisKhan/Student' 
         }
      }
      
      stage('maven build'){      
                steps{
              sh 'mvn package'
          }
      }
        stage("build and run docker images"){
            steps{
                sh 'docker-compose up -d'
            }
        }
      }
}
